#define INTERACT_GENERIC "interact_basic" // "interact"
#define INTERACT_HELP "interact_basic" // "help"
#define INTERACT_DISARM "interact_basic" // "disarm"
#define INTERACT_HARM "interact_basic" // "harm"
#define INTERACT_GRAB "interact_basic" // "grab"
#define INTERACT_PULL "interact_basic" // "pull"
#define INTERACT_UNPULL "interact_basic" // "unpull"
